# 0. Talk about jupyter-notebooks (optional in case people don't know)
- Each cell is independent and can be run separately.
- Even after deleting a cell if it was run, the variables in that cell are still a part of the memory
- Talk about sessions
- Talk about '!' command to run linux commands
- Talk about %time
- Markdown and code cells
- Some common keybindings: j, k, a, b, shift+enter, ctrl+enter, ctrl+z for undo, ctrl+a, double click, triple click
- talk about drive integration
- talk about gpu integration

In [ ]:
import pandas as pd

- Why pandas?
- why csvs?

## 1.1 Reading csvs
This command parses a csv file and converts it into a pandas dataframe

In [ ]:
df = pd.read_csv("housing.csv")
df

         city  area  floor    price
0       Delhi  1200      3  5000000
1      Mumbai  1500      2  7000000
2   Bangalore  1000      1  4000000
3     Chennai  1300      4  6000000
4   Hyderabad  1100      2  4500000
5     Kolkata  1400      3  5500000
6        Pune   900      1  3500000
7   Ahmedabad  1600      4  6500000
8       Surat  1050      2  4200000
9      Jaipur  1250      3  5200000
10     Kanpur   800      1  3000000
11    Lucknow  1150      2  4300000
12     Nagpur   950      1  3800000
13     Indore  1350      3  5300000
14   Vadodara  1000      2  4000000

## 1.2 Shape, rows and columns
Commands to find the shape of the dataset, get the number of columns and rows

In [ ]:
# Getting information about the shape of the dataset
print(f"The shape of the dataset is as follows: {df.shape}")
print(f"No. of rows: {df.shape[0]}")
print(f"No. of columns: {df.shape[1]}")

The shape of the dataset is as follows: (15, 4)
No. of rows: 15
No. of columns: 4

## 1.3 Head and tail
The head commands lets you see the head of the dataset (the top part)
The tail commands lets you see the tail of the dataset (the bottom part)

In [ ]:
# displays the first 5 rows of the dataset
df.head()

        city  area  floor    price
0      Delhi  1200      3  5000000
1     Mumbai  1500      2  7000000
2  Bangalore  1000      1  4000000
3    Chennai  1300      4  6000000
4  Hyderabad  1100      2  4500000

In [ ]:
# you can pass a parameter that displays the exact amount of records that you want
df.head(10)

        city  area  floor    price
0      Delhi  1200      3  5000000
1     Mumbai  1500      2  7000000
2  Bangalore  1000      1  4000000
3    Chennai  1300      4  6000000
4  Hyderabad  1100      2  4500000
5    Kolkata  1400      3  5500000
6       Pune   900      1  3500000
7  Ahmedabad  1600      4  6500000
8      Surat  1050      2  4200000
9     Jaipur  1250      3  5200000

In [ ]:
# displaying the last 5 records from the dataset
df.tail()

        city  area  floor    price
10    Kanpur   800      1  3000000
11   Lucknow  1150      2  4300000
12    Nagpur   950      1  3800000
13    Indore  1350      3  5300000
14  Vadodara  1000      2  4000000

In [ ]:
# adding a parameter specifying the number of lines to display
df.tail(10)

         city  area  floor    price
5     Kolkata  1400      3  5500000
6        Pune   900      1  3500000
7   Ahmedabad  1600      4  6500000
8       Surat  1050      2  4200000
9      Jaipur  1250      3  5200000
10     Kanpur   800      1  3000000
11    Lucknow  1150      2  4300000
12     Nagpur   950      1  3800000
13     Indore  1350      3  5300000
14   Vadodara  1000      2  4000000

## 1.3 Info, describe commands
- Info lets you see the null values and datatypes for each column
- Describe gives you a statistical description of the numerical column

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   city    15 non-null     object
 1   area    15 non-null     int64
 2   floor   15 non-null     int64
 3   price   15 non-null     int64
dtypes: int64(3), object(1)
memory usage: 608.0+ bytes

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
area,15.0,1.170000e+03,2.297514e+02,800.0,1000.0,1150.0,1325.0,1600.0
floor,15.0,2.266667e+00,1.032796e+00,1.0,1.5,2.0,3.0,4.0
price,15.0,4.786667e+06,1.134439e+06,3000000.0,4000000.0,4500000.0,5400000.0,7000000.0

## 1.4 Iloc and loc
- Used for selecting data
- Basically the 'SELECT' query from SQL for dataframes

In [ ]:
# entries from 3rd row till last
df.iloc[11:]

        city  area  floor    price
11   Lucknow  1150      2  4300000
12    Nagpur   950      1  3800000
13    Indore  1350      3  5300000
14  Vadodara  1000      2  4000000

In [ ]:
# entries from first 3 rows
df.iloc[:3]

        city  area  floor    price
0      Delhi  1200      3  5000000
1     Mumbai  1500      2  7000000
2  Bangalore  1000      1  4000000

In [ ]:
# entries for the first 2 columns
df.iloc[:, :2]

         city  area
0       Delhi  1200
1      Mumbai  1500
2   Bangalore  1000
3     Chennai  1300
4   Hyderabad  1100
5     Kolkata  1400
6        Pune   900
7   Ahmedabad  1600
8       Surat  1050
9      Jaipur  1250
10     Kanpur   800
11    Lucknow  1150
12     Nagpur   950
13     Indore  1350
14   Vadodara  1000

In [ ]:
# entries of the last column
df.iloc[:, 3:].head(5)

     price
0  5000000
1  7000000
2  4000000
3  6000000
4  4500000

In [ ]:
df.loc[1:3]
# notice how 3 is inclusive

        city  area  floor    price
1     Mumbai  1500      2  7000000
2  Bangalore  1000      1  4000000
3    Chennai  1300      4  6000000

In [ ]:
df.iloc[1:3]
# notice how 3 is exclusive

        city  area  floor    price  rooms
1     Mumbai  1500      2  7000000      3
2  Bangalore  1000      1  4000000      1

In [ ]:
df.loc[(df.city == "Mumbai")]

     city  area  floor    price
1  Mumbai  1500      2  7000000

In [ ]:
df.loc[(df.city.isin(["Mumbai", "Hyderabad", "Chennai", "Bangalore"]))]

        city  area  floor    price
1     Mumbai  1500      2  7000000
2  Bangalore  1000      1  4000000
3    Chennai  1300      4  6000000
4  Hyderabad  1100      2  4500000

In [ ]:
df.loc[(df.area > 1000) & (df.floor == 2)]

         city  area  floor    price
1      Mumbai  1500      2  7000000
4   Hyderabad  1100      2  4500000
8       Surat  1050      2  4200000
11    Lucknow  1150      2  4300000

## 1.5 Drop
- Dropping rows and columns

In [ ]:
# Create a copy with the first 10 records
df_copy = df[:10]
df_copy

        city  area  floor    price  rooms
0      Delhi  1200      3  5000000      2
1     Mumbai  1500      2  7000000      3
2  Bangalore  1000      1  4000000      1
3    Chennai  1300      4  6000000      3
4  Hyderabad  1100      2  4500000      2
5    Kolkata  1400      3  5500000      3
6       Pune   900      1  3500000      1
7  Ahmedabad  1600      4  6500000      3
8      Surat  1050      2  4200000      2
9     Jaipur  1250      3  5200000      3

In [ ]:
# drop the city column
df_copy.drop(columns = "city")

   area  floor    price
0  1200      3  5000000
1  1500      2  7000000
2  1000      1  4000000
3  1300      4  6000000
4  1100      2  4500000
5  1400      3  5500000
6   900      1  3500000
7  1600      4  6500000
8  1050      2  4200000
9  1250      3  5200000

In [ ]:
# drop the second record specifically
df_copy.drop(index = 2)

        city  area  floor    price  rooms
0      Delhi  1200      3  5000000      2
1     Mumbai  1500      2  7000000      3
3    Chennai  1300      4  6000000      3
4  Hyderabad  1100      2  4500000      2
5    Kolkata  1400      3  5500000      3
6       Pune   900      1  3500000      1
7  Ahmedabad  1600      4  6500000      3
8      Surat  1050      2  4200000      2
9     Jaipur  1250      3  5200000      3

In [ ]:
# drop 3rd and 4rd records with horizontal axis
df_copy.drop([3, 4], axis = 0)

        city  area  floor    price  rooms
0      Delhi  1200      3  5000000      2
1     Mumbai  1500      2  7000000      3
2  Bangalore  1000      1  4000000      1
5    Kolkata  1400      3  5500000      3
6       Pune   900      1  3500000      1
7  Ahmedabad  1600      4  6500000      3
8      Surat  1050      2  4200000      2
9     Jaipur  1250      3  5200000      3

In [ ]:
# drop the "floor" column with axis
df_copy.drop("floor", axis = 1)

        city  area    price  rooms
0      Delhi  1200  5000000      2
1     Mumbai  1500  7000000      3
2  Bangalore  1000  4000000      1
3    Chennai  1300  6000000      3
4  Hyderabad  1100  4500000      2
5    Kolkata  1400  5500000      3
6       Pune   900  3500000      1
7  Ahmedabad  1600  6500000      3
8      Surat  1050  4200000      2
9     Jaipur  1250  5200000      3

In [ ]:
df.tail(1)

        city  area  floor    price
14  Vadodara  1000      2  4000000

## 1.7 Concatenation
- Adding rows to the dataset
- Adding new columns to the dataset
- Merging datasets

In [ ]:
# Add an extra record at the bottom of the table
extra_flat = pd.DataFrame({"city": ["Vadodara"], "area": [1000], "floor": [2], "price": [4000000]})
df = pd.concat([df, extra_flat], axis =0, ignore_index = True)
df

         city  area  floor    price
0       Delhi  1200      3  5000000
1      Mumbai  1500      2  7000000
2   Bangalore  1000      1  4000000
3     Chennai  1300      4  6000000
4   Hyderabad  1100      2  4500000
5     Kolkata  1400      3  5500000
6        Pune   900      1  3500000
7   Ahmedabad  1600      4  6500000
8       Surat  1050      2  4200000
9      Jaipur  1250      3  5200000
10     Kanpur   800      1  3000000
11    Lucknow  1150      2  4300000
12     Nagpur   950      1  3800000
13     Indore  1350      3  5300000
14   Vadodara  1000      2  4000000
15   Vadodara  1000      2  4000000

In [ ]:
# Add a new column "rooms" containing the rooms for each flat
bedrooms = pd.DataFrame({"rooms": [2, 3, 1, 3, 2, 3, 1, 3, 2, 3, 1, 2, 1, 3, 1, 1]})
df = pd.concat([df, bedrooms], axis = 1)
df

         city  area  floor    price  rooms
0       Delhi  1200      3  5000000      2
1      Mumbai  1500      2  7000000      3
2   Bangalore  1000      1  4000000      1
3     Chennai  1300      4  6000000      3
4   Hyderabad  1100      2  4500000      2
5     Kolkata  1400      3  5500000      3
6        Pune   900      1  3500000      1
7   Ahmedabad  1600      4  6500000      3
8       Surat  1050      2  4200000      2
9      Jaipur  1250      3  5200000      3
10     Kanpur   800      1  3000000      1
11    Lucknow  1150      2  4300000      2
12     Nagpur   950      1  3800000      1
13     Indore  1350      3  5300000      3
14   Vadodara  1000      2  4000000      1
15   Vadodara  1000      2  4000000      1

## 1.8 Miscellaneous
- Dropping duplicates
- Looking at unique values and nuniques
- finiding nulls in the dataset

In [ ]:
# drop duplicates when necessary
df = df.drop_duplicates()
df

         city  area  floor    price  rooms
0       Delhi  1200      3  5000000      2
1      Mumbai  1500      2  7000000      3
2   Bangalore  1000      1  4000000      1
3     Chennai  1300      4  6000000      3
4   Hyderabad  1100      2  4500000      2
5     Kolkata  1400      3  5500000      3
6        Pune   900      1  3500000      1
7   Ahmedabad  1600      4  6500000      3
8       Surat  1050      2  4200000      2
9      Jaipur  1250      3  5200000      3
10     Kanpur   800      1  3000000      1
11    Lucknow  1150      2  4300000      2
12     Nagpur   950      1  3800000      1
13     Indore  1350      3  5300000      3
14   Vadodara  1000      2  4000000      1

In [ ]:
# finding the number of nulls in each column
df.isna().sum()
# or df.isnull().sum()

city     0
area     0
floor    0
price    0
rooms    0
dtype: int64

In [ ]:
# print the number of unique values in the "city" column and the unique values themselves
print("The no. of unique values in city column: ", df["city"].nunique())
print("The unique values in city column: ", df["city"].unique())

The no. of unique values in city column:  15
The unique values in city column:  ['Delhi' 'Mumbai' 'Bangalore' 'Chennai' 'Hyderabad' 'Kolkata' 'Pune'
 'Ahmedabad' 'Surat' 'Jaipur' 'Kanpur' 'Lucknow' 'Nagpur' 'Indore'
 'Vadodara']

## 1.9 Groupby
- Groups data by a particular column(s) and applies aggregate functions like sum, mean, or count.

In [ ]:
# Group the flats according to rooms and mention their count
df.groupby("rooms")['price'].count()

rooms
1    5
2    4
3    6
Name: price, dtype: int64

In [ ]:
# Here we are grouping by floor and mentioning the mean price
df.groupby("floor")['price'].mean()

floor
1    3575000.0
2    4800000.0
3    5250000.0
4    6250000.0
Name: price, dtype: float64

# 2. Matplotlib and seaborn
- heatmap
- bar plot
- histogram
- line plot
- scatter plot
- pie chart

In [ ]:
# Chirag's part

# 3. Numpy
- reshape
- mean
- ndarray
- sum
- axis -> explain
- stack methods -> learn

In [ ]:
# Chirag's part

# 4. Scikit-learn
- train, test, validation
- cross_validation
- fitting
- predict
- cross_val_score
- accuracy, mae, rmse, r^2
- confusion matrix??
- linear regression, decision-tree

## 4.1 Splitting into X and y

In [ ]:
# Split the dataset into X and y
X = df[["city", "area", "floor", "rooms"]]
y = df["price"]
X.head(5)

        city  area  floor  rooms
0      Delhi  1200      3      2
1     Mumbai  1500      2      3
2  Bangalore  1000      1      1
3    Chennai  1300      4      3
4  Hyderabad  1100      2      2

In [ ]:
y.head(5)

0    5000000
1    7000000
2    4000000
3    6000000
4    4500000
Name: price, dtype: int64

## 4.3 Splitting into training and testing data
- Why do we need to split into training and testing data?
- Isn't more data always better?

In [ ]:
# Split X and y into training and testing datasets here
from sklearn.model_selection import train_test_split
x_train, y_train, x_test, y_test = train_test_split(X, y, test_size=0.2)
X.head(5)

        city  area  floor  rooms
0      Delhi  1200      3      2
1     Mumbai  1500      2      3
2  Bangalore  1000      1      1
3    Chennai  1300      4      3
4  Hyderabad  1100      2      2

## 4.3 The general flow of ML process

![image.png]()

## 4.4 Understanding metrics
- What are metrics?
- Why do we need metrics?
- What goes into selecting a metric?

In [ ]:
# calculating mean absolute error on predictions and actual values
from sklearn.metrics import mean_absolute_error
from numpy import mean
predicted = [3, 4, 5, 6]
actual    = [2.9, 4.2, 5.5, 5.8]
mae = mean_absolute_error(actual, predicted)
maep = mae * 100 / mean(actual)
print("The mean absolute error is: ", round(mae, 2))
print("The mean absolute error percentage is: ", round(maep, 2), "%")

The mean absolute error is:  0.25
The mean absolute error percentage is:  5.43 %

![image.png]()

In [ ]:
# calculate precision, recall, accuracy_score
from sklearn.metrics import accuracy_score, precision_score, recall_score
predicted = [0, 0, 1, 1, 1, 1]
actual    = [1, 1, 0, 1, 1, 1]
print("The accuracy of our model is: ", accuracy_score(actual, predicted))
print("The recall of our model is: ", recall_score(actual, predicted))
print("The precision of our model is: ", precision_score(actual, predicted))

The accuracy of our model is:  0.5
The recall of our model is:  0.6
The precision of our model is:  0.75